### ISSUE TITLE
Warn if trying to print the "signed acceptance" without authorized amounts

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#27] opened 2016-03-27 21:47 UTC
With KDE starting to use this software, we are facing the problem that lots of people seem to be printing the signed acceptance before setting the amounts of the reimbursement, this is unfortunate since we need to roll back the reimbursement, they have to print+sign+scan again, losing some time.

It would be nice if you would get a warning if you press the "Download printable version" it no authorized value is set for any of the fields.

What do you think? I can try to do this if you point me in the right direction.

**Comment by ancorgs** [comment] 2016-04-04 07:27
@tsdgeos Sorry, I have had very limited Internet access and spare time in the last weeks (moving to a new house). I'll take a look to it this week.

**Comment by colomar** [comment] 2016-04-08 15:29
The whole process is quite confusing. For the person requesting the reimbursement, it is not at all clear why they even have to authorize positions in different currencies separately.
There is just a form which for some reason has "XX" in one table row but an edit field in another, with no explanation.
Then one wonders why the sum on the printed reimbursement form isn't what was approved before.
Therefore, the warning should not only say "You have unauthorized positions in your request", but actually explain what one has to enter where and why. 
Ideally, this should be explained directly when filling out the form.

**Comment by ancorgs** [comment] 2016-04-22 12:12
Not sure if I fully understand the suggestions done by @colomar. It would be nice to open a separate issue for them, so we can discuss with examples, screenshots and so on.

About the original $SUBJECT, it should be doable (even easy) to run the validation of the reimbursement before displaying the pdf and, thus, displaying a pop-up saying something like "some important info is missing, so the pdf you are going to see is not a final version".... with better wording, of course.

**Comment by colomar** [comment] 2016-04-22 12:22
@ancorgs The problem is that it is not at all clear for those requesting a reimbursement that positions in different currencies have to be authorized separately, or _why_, or _how_ to do that.

It that separate authorization is necessary at all (preferably it would just all be automatic with no user interaction needed), would it perhaps make sense to put a message somewhere stating something like
"Your request contains positions in different currencies. If the approved amounts are correct, please enter them again in the fields below" ?

**Closed** 2016-04-25 14:15 UTC
